queries:
  - 'proton therapy'
  - 'particle therapy'
  - 'hadron therapy'
  - 'carbon ion therapy'
  - 'ion beam therapy'
  - 'proton radiotherapy'
  - 'adaptive proton therapy'
  - 'proton beam therapy'
  - 'carbon ion radiotherapy'
  - 'hadron radiotherapy'
