repos:
  - url: https://github.com/e0404/matRad
    always_include: true
    note: Nice open-source radiotherapy treatment planning toolkit;
    tags:
      - treatment planning
      - software tool

  - url: https://github.com/opaserr/dota
    always_include: true
    note: Transformer-based dose calculation for proton and photon
    tags: 
      - dose calculation
      - transformer  

